### PR TITLE
Fix author links

### PR DESCRIPTION
**Pull request by falgon**

### CODE REVIEW

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/510)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/9d836e7a-f275-4011-ac0d-85333ed8abb5/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/511)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/f39998e8-97cf-4453-b623-cd3e8f3788dc/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/512)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/4a23d574-96b4-4b9a-8817-5060cf305382/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/513)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/b71d78e6-7370-46a8-acb7-6ddfdc88450f/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/514)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/85aa481d-b670-47f9-95e8-0ae7b6bc044c/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/515)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/aaa9c812-8049-4035-89d1-6ff11d576260/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/516)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/0203c14e-b135-4bc4-8e6b-091fbcb97d6c/artifacts/0/index.html>

**Comment by falgon** [comment]
ToDo:fa-brands -> fab

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/517)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/718e4080-916f-4c95-8b66-b410fddc4c47/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/518)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/8ed4a362-3f6f-4211-9496-f7d0fe6c5e79/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/519)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/80f148ff-9f3a-40c7-95db-535b50be80f3/artifacts/0/index.html>

**Pull request merged**
