### PR TITLE
Add animation for the top page

### PR DESCRIPTION
**Pull request by falgon**

### CODE REVIEW

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/487)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/1dfa498f-ad5c-4542-b544-f6a99086463e/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/489)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/6cca85f6-dca5-4382-9dcd-e27894a26215/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/490)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/df6accfe-634b-40be-8184-87994490842c/artifacts/0/index.html>

**Comment by kiirotori** [comment]
* [Build log](https://circleci.com/gh/falgon/roki-web/491)
* Preview build with this PR (commit): <https://output.circle-artifacts.com/output/job/5636ee93-61a6-4f97-a997-1c5160fad9e7/artifacts/0/index.html>

**Comment by falgon** [comment]
When I saw the preview, I felt that the production was not good enough, so I stopped

**Pull request closed without merging**
